import { REQUIRED_ENV, type ManagedProvider } from "./types";

export const PROVIDERS: ManagedProvider[] = [
  {
    id: "railway",
    name: "Railway",
    tagline: "Easiest all-in-one: app + Postgres in one project.",
    bestFor: "First-time deploys. Dockerfile is auto-detected.",
    postgres: "Included — add the Postgres plugin to the same project.",
    sleeps: "Services do not sleep; usage accrues while running.",
    cost: "One-time $5 trial credit for new accounts, then usage-based (~$5/mo entry).",
    steps: [
      "Open Railway and create a New Project → Deploy from GitHub repo (select your chatflow-ai fork, service root: customer-backend/).",
      "Add a Postgres plugin to the project (New → Database → Postgres).",
      "On the app service → Variables: set DATABASE_URL to the Postgres reference (${{Postgres.DATABASE_URL}}), plus META_APP_SECRET, WEBHOOK_VERIFY_TOKEN, BACKEND_AUTH_TOKEN, IG_ACCOUNT_ID / IG_USERNAME / META_ACCESS_TOKEN, ENCRYPTION_KEY.",
      "Deploy, then open the service → Settings → Networking → Generate Domain. That public URL is your backend URL.",
      "Paste the URL + BACKEND_AUTH_TOKEN in the connect form below and hit Connect & Verify.",
    ],
    envVars: REQUIRED_ENV,
    links: [{ label: "Open Railway", url: "https://railway.com/new" }],
  },
  {
    id: "render",
    name: "Render + Neon/Supabase",
    tagline: "Free app hosting (with sleep) + free external Postgres.",
    bestFor: "Zero-cost start when you accept cold starts + uptime pings.",
    postgres: "Bring your own — Render's free Postgres expires 30 days after creation, so use Neon or Supabase free tier and paste its DATABASE_URL.",
    sleeps: "Free web services sleep after 15 idle min and wake in ~1 min on the next request. A 5-min UptimeRobot ping keeps it warm but consumes the 750h monthly free budget — enable only if you see missed events.",
    cost: "Free tier available; paid from ~$7/mo to remove sleep.",
    steps: [
      "Create a free Postgres at Neon or Supabase and copy the connection string (use the pooled/pgbouncer host if offered).",
      "On Render: New → Blueprint → connect your repo (render.yaml in customer-backend/ is included).",
      "Set env vars, with DATABASE_URL pointing at the Neon/Supabase string.",
      "Deploy and copy the service URL (https://xxx.onrender.com).",
      "Paste the URL + BACKEND_AUTH_TOKEN in the connect form below and hit Connect & Verify.",
    ],
    envVars: REQUIRED_ENV,
    links: [
      { label: "Render Blueprint deploy", url: "https://dashboard.render.com/select-repo?type=blueprint" },
      { label: "Neon", url: "https://neon.tech" },
      { label: "Supabase", url: "https://supabase.com/dashboard" },
    ],
  },
  {
    id: "supabase-db",
    name: "Supabase (database)",
    tagline: "Use Supabase purely as the database; host the app elsewhere.",
    bestFor: "Users who already have Supabase, or want its dashboard/backups.",
    postgres: "This IS the Postgres — pair with Railway/Render/Fly for the app container.",
    sleeps: "Free projects pause after inactivity — resume from the dashboard; the app reconnects automatically.",
    cost: "Generous free tier; restores/backups improve on paid plans.",
    steps: [
      "Create a Supabase project → Project Settings → Database → copy the connection string (use port 6543 pooler host for hosted apps).",
      "Deploy customer-backend/ on Railway, Render, or Fly.io with DATABASE_URL set to that string plus the remaining env vars.",
      "Paste the app URL + BACKEND_AUTH_TOKEN in the connect form below and hit Connect & Verify.",
    ],
    envVars: REQUIRED_ENV,
    links: [{ label: "Supabase dashboard", url: "https://supabase.com/dashboard" }],
  },
  {
    id: "fly",
    name: "Fly.io",
    tagline: "Docker-native global hosting with a real CLI.",
    bestFor: "Developers comfortable with a terminal; great uptime habits.",
    postgres: "Bring your own (Fly Postgres costs) or use Neon/Supabase free and set DATABASE_URL.",
    sleeps: "Machines auto-stop by default — set auto_stop_machines = off for the webhook receiver, or use suspend-aware min_machines_running = 1.",
    cost: "Small free allowances; a single shared machine is a few dollars/month.",
    steps: [
      "Install flyctl and run: fly auth login.",
      "In customer-backend/: fly launch (Dockerfile is detected — decline Postgres if using Neon/Supabase).",
      "Set secrets: fly secrets set DATABASE_URL=... META_APP_SECRET=... WEBHOOK_VERIFY_TOKEN=... BACKEND_AUTH_TOKEN=... (plus Instagram + optional AI vars).",
      "Run: fly deploy. Your URL is https://<app-name>.fly.dev.",
      "Paste the URL + BACKEND_AUTH_TOKEN in the connect form below and hit Connect & Verify.",
    ],
    envVars: REQUIRED_ENV,
    links: [{ label: "Fly.io docs", url: "https://fly.io/docs" }],
  },
];
